### PR TITLE
Fix: Fade out options not working

### PR DESCRIPTION
**Pull request by jalovatt**
_main()_'s if/then/else logic wasn't using the _input_ values in the same order that they were given by the dialog box.

### CODE REVIEW

**Comment by jalovatt** [comment]
Also, the wording in the dialog box is a little confusing IMO. Perhaps "Keep", "Ignore", "Exclude"?

**Comment by X-Raym** [comment]
@jalovatt I'm surprised there was an error, but I'll trust you on this 🐱 
If is one of my early script, if I had to recode it, I will indeed change the wording, and most of all, add shortcuts and aliases, like "0/n/false/exclude/e/x" for exclude and "1/y/true/keep/k" for keeping, and simply "i" for ignore, and the whole feeling case insensitive.

But I don't know how much this script is used, it may not worth that level of attention ^^ Unless you want to update it, I'll merge the pull request as it is.

**Comment by jalovatt** [comment]
I just had a look and it would need a bit of recoding for my wording to make sense. Don't worry about it.

**Comment by X-Raym** [comment]
@jalovatt Thanks for your contribution !

**Pull request merged**
