### PR TITLE
Update Random Volume and Pitch GUI scripts

### PR DESCRIPTION
**Pull request by ausbaxter**
Volume randomizer is now predictable on non-unity gain takes
Pitch randomizer will not overwrite existing take pitch offsets

### CODE REVIEW

**Comment by X-Raym** [comment]
@ausbaxter Hi, thanks for your contribution,

https://github.com/X-Raym/REAPER-ReaScripts/pull/5/commits/8c754c84438003fb7413eb102e1e5bb13212cd32

I'm not sure the Nudge Volume fix is required, as the bug report [here](https://forum.cockos.com/showthread.php?p=1951080#post1951080) seems not to be a bug. Else, please show screen capture of before/after the modification.

https://github.com/X-Raym/REAPER-ReaScripts/pull/5/commits/a88be24b4840fa72e59a1916ed1267184dbdb53a

I prefer it overwrites existing pan so we can re-do a randomizing session from scratch. Sure we could use a Reset Pan action. But as I prefer this behavior to be the default (it is the one I need), I would prefer that this `Update Random Take Pitch` only applied if a button is toggle (and non active by default). Are you ok with that ?

**Comment by ausbaxter** [comment]
Thanks for your reply,

I replied to your post on this thread regarding the nudge volume.
https://forum.cockos.com/showthread.php?p=1951271&posted=1#post1951271

I see what you mean about redoing the randomization from scratch, it is nice not having to undo. In that case you can probably ignore these changes haha.

**Comment by X-Raym** [comment]
@ausbaxter 
https://github.com/X-Raym/REAPER-ReaScripts/pull/5/commits/33ed36a1893c5bee6ce593399483a8a968cd2246
This file isn't put at the right subfolder :S

Don't you think it would be better to have an Apply button for setting with a reset and an Offset buttons so it can offset existing values ? This would be a way to have the desired I prefer (Apply), and the one you prefer (Offset).

**Comment by X-Raym** [comment]
I close this cause these script deserve better GUI anyway now 😉

**Pull request closed without merging**
